import { CommandPermission } from "./types";

export const TOWNY_PERMISSIONS: CommandPermission[] = [
    { command: "/towny map", permission: "all" },
    { command: "/towny map big", permission: "all" },
    { command: "/towny map hud", permission: "all" },
    { command: "/towny hud", permission: "all" },
    { command: "/towny prices", permission: "all" },
    { command: "/towny time", permission: "all" },
    { command: "/towny universe", permission: "all" },
    { command: "/towny top balance", permission: "all" },
    { command: "/towny top land", permission: "all" },
    { command: "/towny top residents", permission: "all" },
    { command: "/towny spy", permission: "admin" },
    { command: "/towny version", permission: "all" },
    { command: "/towny farmblocks", permission: "all" },
    { command: "/towny switches", permission: "all" },
    { command: "/towny itemuse", permission: "all" },

    // plot
    { command: "/plot claim", permission: "all" },
    { command: "/plot claim auto", permission: "all" },
    { command: "/plot unclaim", permission: "all" },
    { command: "/plot forsale", permission: "all" },
    { command: "/plot notforsale", permission: "all" },
    { command: "/plot evict", permission: "all" },
    { command: "/plot set", permission: "all" },
    { command: "/plot set name", permission: "all" },
    { command: "/plot toggle", permission: "all" },
    { command: "/plot toggle pvp", permission: "all" },
    { command: "/plot toggle explosion", permission: "all" },
    { command: "/plot toggle fire", permission: "all" },
    { command: "/plot toggle mob", permission: "all" },
    { command: "/plot trust add", permission: "all" },
    { command: "/plot trust remove", permission: "all" },
    { command: "/plot perm gui", permission: "all" },
    { command: "/plot district create", permission: "all" },
    { command: "/plot clear", permission: "all" },

    // resident
    { command: "/resident", permission: "all" },
    { command: "/resident list", permission: "all" },
    { command: "/resident friend add", permission: "all" },
    { command: "/resident friend remove", permission: "all" },
    { command: "/resident plotlist", permission: "all" },
    { command: "/resident jail paybail", permission: "all" },
    { command: "/resident spawn", permission: "all" },
    { command: "/resident set perm", permission: "all" },
    { command: "/resident toggle map", permission: "all" },
    { command: "/resident toggle townclaim", permission: "all" },
    { command: "/resident toggle plotborder", permission: "all" },
    { command: "/resident toggle pvp", permission: "all" },
    { command: "/resident toggle spy", permission: "supporter" },
    { command: "/resident tax", permission: "all" },

    // town — все игроки
    { command: "/town", permission: "all" },
    { command: "/town here", permission: "all" },
    { command: "/town list", permission: "all" },
    { command: "/town online", permission: "all" },
    { command: "/town join", permission: "all" },
    { command: "/town spawn", permission: "all" },
    { command: "/town deposit", permission: "all" },
    { command: "/town outlawlist", permission: "all" },
    { command: "/town jail list", permission: "all" },
    { command: "/town outpost", permission: "all" },
    { command: "/town outpost list", permission: "all" },
    { command: "/town plots", permission: "all" },
    { command: "/town baltop", permission: "all" },
    { command: "/town reslist", permission: "all" },
    { command: "/town ranklist", permission: "all" },
    { command: "/town say", permission: "all" },

    // town — житель
    { command: "/town leave", permission: "all", roles: ["Житель"] },

    // town — мэр и заместитель
    { command: "/town new", permission: "all", roles: ["Мэр"] },
    { command: "/town add", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town kick", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town claim", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town claim auto", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town claim outpost", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town unclaim", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town set board", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town set homeblock", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town set spawn", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town set plotprice", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town rank add", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town rank remove", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town outlaw add", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town outlaw remove", permission: "all", roles: ["Мэр", "Заместитель"] },
    { command: "/town jail", permission: "all", roles: ["Мэр", "Заместитель"] },

    // town — только мэр
    { command: "/town withdraw", permission: "all", roles: ["Мэр"] },
    { command: "/town set mayor", permission: "all", roles: ["Мэр"] },
    { command: "/town set taxes", permission: "all", roles: ["Мэр"] },
    { command: "/town set plottax", permission: "all", roles: ["Мэр"] },
    { command: "/town toggle explosion", permission: "all", roles: ["Мэр"] },
    { command: "/town toggle fire", permission: "all", roles: ["Мэр"] },
    { command: "/town toggle mobs", permission: "all", roles: ["Мэр"] },
    { command: "/town toggle pvp", permission: "all", roles: ["Мэр"] },
    { command: "/town toggle open", permission: "all", roles: ["Мэр"] },
    { command: "/town toggle public", permission: "all", roles: ["Мэр"] },
    { command: "/town merge", permission: "all", roles: ["Мэр"] },
    { command: "/town delete", permission: "all", roles: ["Мэр"] },
    { command: "/town buy bonus", permission: "all", roles: ["Мэр"] },
    { command: "/town purge", permission: "all", roles: ["Мэр"] },

    // town — бывший житель
    { command: "/town reclaim", permission: "all", roles: ["Быв.Житель"] },

    // invite
    { command: "/invite list", permission: "all" },
    { command: "/invite accept", permission: "all" },
    { command: "/invite deny", permission: "all" },

    // nation — все участники
    { command: "/nation", permission: "all" },
    { command: "/nation list", permission: "all" },
    { command: "/nation online", permission: "all" },
    { command: "/nation leave", permission: "all" },
    { command: "/nation spawn", permission: "all" },
    { command: "/nation allylist", permission: "all" },
    { command: "/nation enemylist", permission: "all" },

    // nation — король и заместитель
    { command: "/nation add", permission: "all", roles: ["Король", "Заместитель"] },
    { command: "/nation kick", permission: "all", roles: ["Король", "Заместитель"] },
    { command: "/nation ally add", permission: "all", roles: ["Король", "Заместитель"] },
    { command: "/nation ally remove", permission: "all", roles: ["Король", "Заместитель"] },
    { command: "/nation enemy add", permission: "all", roles: ["Король", "Заместитель"] },
    { command: "/nation enemy remove", permission: "all", roles: ["Король", "Заместитель"] },

    // nation — только король
    { command: "/nation new", permission: "all", roles: ["Король"] },
    { command: "/nation deposit", permission: "all", roles: ["Король"] },
    { command: "/nation withdraw", permission: "all", roles: ["Король"] },
    { command: "/nation set king", permission: "all", roles: ["Король"] },
    { command: "/nation set capital", permission: "all", roles: ["Король"] },
    { command: "/nation set taxes", permission: "all", roles: ["Король"] },
    { command: "/nation set tag", permission: "all", roles: ["Король"] },
    { command: "/nation toggle neutral", permission: "all", roles: ["Король"] },
    { command: "/nation toggle open", permission: "all", roles: ["Король"] },
    { command: "/nation merge", permission: "all", roles: ["Король"] },
    { command: "/nation delete", permission: "all", roles: ["Король"] },

    // townyadmin (/ta)
    { command: "/ta town new", permission: "admin" },
    { command: "/ta town delete", permission: "admin" },
    { command: "/ta town set mayor", permission: "admin" },
    { command: "/ta town set name", permission: "admin" },
    { command: "/ta town unruin", permission: "admin" },
    { command: "/ta givebonus", permission: "admin" },
    { command: "/ta newday", permission: "admin" },
    { command: "/ta purge", permission: "admin" },
    { command: "/ta reload all", permission: "admin" },
    { command: "/ta resident delete", permission: "admin" },

    // townyworld (/tw)
    { command: "/tw list", permission: "admin" },
    { command: "/tw toggle claimable", permission: "admin" },
    { command: "/tw toggle pvp", permission: "admin" },
    { command: "/tw toggle forcepvp", permission: "admin" },
    { command: "/tw toggle warallowed", permission: "admin" },
    { command: "/tw toggle town crystal", permission: "admin" },
    { command: "/tw set worldmode", permission: "admin" },
];